### ISSUE TITLE
Creating a windows detector failed and generates a lot of shards reaching the cluster limit everyday

### ISSUE THREAD

**Issue by mareban** [opensearch-project/security-analytics#509]
Hello ,

We've tried to create a windows detector using all the rules ! It failed and ask to review the configuration !
So no detector is created, but we have a lot of .opensearch-sap-windows-detectors-queries* created each day :-(, and we don't know how to clean this and create the detector sucessfully !

**How can one reproduce the bug?**
create the windows detector with all rules selected on winlogbeat-* indices !

**What is the expected behavior?**
Create the detector and notify us on security events

**What is your host/environment?**
the 2.8.0 Opensearch cluster is running on Ubuntu 22.04.2

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by mareban** [comment]
For info, monitoring jobs, we have this kind of jobs always running :  

GET _cat/pending_tasks

3525231 120ms HIGH put-mapping [.opensearch-sap-windows-detectors-queries-000029/1OPPMM8SQoSHDX5WpdSHUw]
3525380 1s HIGH put-mapping [.opensearch-sap-windows-detectors-queries-000035/ITm-ofAJT1G5UXL8uBQ71w]
3525404 100ms NORMAL rollover_index source [.opensearch-sap-windows-detectors-queries-000037] to target [.opensearch-sap-windows-detectors-queries-000038]
 
 shards example  : 
 .opensearch-sap-windows-detectors-queries-000037     0 r STARTED

 Thanks for your help

**Comment by praveensameneni** [comment]
@mareban , Thank you for trying out Security Analytics. Can you share couple of sample log files (with the necessary redacted data).

**Comment by sbcd90** [comment]
hi @mareban , do you have any ism policy defined for the index-pattern `winlogbeat-*`? or how many concrete indices are there behind the pattern `winlogbeat-*`?

**Comment by sbcd90** [comment]
hi @mareban , i followed the following steps while running detectors on `beats` data.
i built a custom version of beats. https://github.com/sbcd90/beats/tree/main

i created the index template first by exporting it.
```
.\winlogbeat.exe export template
```
i faced 2 errors, field keys `"data_stream"` & `"priority"` not available.

i then just ran `winlogbeat` with config https://github.com/sbcd90/beats/blob/main/winlogbeat/winlogbeat.yml

i created a `windows` detector with `1580` rules & provided `winlogbeat*` index-pattern as input. 
The detector runs fine generating findings.
![Screenshot 2023-08-09 at 4 00 47 PM](https://github.com/opensearch-project/security-analytics/assets/617607/850b62da-3e60-4ad0-a0e6-fbee16a4c8d6)

![Screenshot 2023-08-09 at 4 00 28 PM](https://github.com/opensearch-project/security-analytics/assets/617607/c4bdeb5b-5a61-4236-ac62-00e892f717dc)

**Comment by sbcd90** [comment]
hi @mareban , i can finally reproduce this issue & understand the problem. will explore options to fix it.
Thanks for creating this issue.
cc: @getsaurabh02

**Comment by mareban** [comment]
> hi @mareban , i followed the following steps while running detectors on `beats` data. i built a custom version of beats. https://github.com/sbcd90/beats/tree/main
> 
> i created the index template first by exporting it.
> 
> ```
> .\winlogbeat.exe export template
> ```
> 
> i faced 2 errors, field keys `"data_stream"` & `"priority"` not available.
> 
> i then just ran `winlogbeat` with config https://github.com/sbcd90/beats/blob/main/winlogbeat/winlogbeat.yml
> 
> i created a `windows` detector with `1580` rules & provided `winlogbeat*` index-pattern as input. The detector runs fine generating findings. ![Screenshot 2023-08-09 at 4 00 47 PM](https://user-images.githubusercontent.com/617607/259569961-850b62da-3e60-4ad0-a0e6-fbee16a4c8d6.png)
> 
> ![Screenshot 2023-08-09 at 4 00 28 PM](https://user-images.githubusercontent.com/617607/259570122-c4bdeb5b-5a61-4236-ac62-00e892f717dc.png)

Hello and Thx again 

Here is what we have when trying to create a windows detector :

![image](https://github.com/opensearch-project/security-analytics/assets/11810873/53f206b4-6332-41b2-8b17-eb65b5b256af)

For the mapping we have 2 field to map with our winlogbeat template ?

![image](https://github.com/opensearch-project/security-analytics/assets/11810873/473d9fb3-240b-476f-85a8-a13dfc0ad9c5)


So , my understanding is that's a bug, and the fix will come soon hopefully :-) ! We are still in 2.8 , and it seems that upgrading to 2.9 will not fix our issue , correct ?


Thank you very much for your help

**Comment by amsiglan** [comment]
Fixed for 2.10 and beyond. We will backport this as part of patch release

**Comment by mareban** [comment]
Thanks for the fix :-) !

We've just upgrade to 2.10 and  still cannot create a windows detector using  all sigma rules for winlogbeat (+500 indicies) !

We have now +60 fields to map, in 2.8 only 2 , and if we don't map anything the detector cannot be created !!


_security_analytics/detectors, params: {}
org.opensearch.securityanalytics.util.SecurityAnalyticsException: Invalid [path] value [message_winlogbeat-__1x8H4YoBiU4cj2_sBud9] for field alias [windows.message_winlogbeat-__1x8H4YoBiU4cj2_sBud9]: an alias must refer to an existing field in the mappings.

and :

[2023-09-29T15:01:04,090][INFO ][o.o.a.t.TransportIndexMonitorAction] [opnscluster-n1] Central Percolation index .opensearch-sap-windows-detectors-queries created
[2023-09-29T15:01:04,154][INFO ][o.o.p.PluginsService     ] [opnscluster-n1] PluginService:onIndexModule index:[.opensearch-sap-windows-detectors-queries-000001/XONDNquhTAyTDL_fs2p0YQ]
[2023-09-29T15:01:04,175][INFO ][o.o.a.u.d.DestinationMigrationCoordinator] [opnscluster-n1] Detected cluster change event for destination migration
[2023-09-29T15:01:04,336][INFO ][o.o.a.u.d.DestinationMigrationCoordinator] [opnscluster-n1] Detected cluster change event for destination migration
[2023-09-29T15:01:15,543][INFO ][o.o.j.s.JobSweeper       ] [opnscluster-n1] Running full sweep
[2023-09-29T15:01:15,601][INFO ][o.o.j.s.JobSweeper       ] [opnscluster-n1] Error while sweeping shard [.opendistro-reports-definitions][0], error message: all shards failed
[2023-09-29T15:01:37,555][INFO ][o.o.c.s.IndexScopedSettings] [opnscluster-n1] [.opensearch-sap-windows-detectors-queries-000001] updating [index.mapping.total_fields.limit] **from [1000] to [5000008]**
[2023-09-29T15:01:37,570][INFO ][o.o.a.u.d.DestinationMigrationCoordinator] [opnscluster-n1] Detected cluster change event for destination migration
[2023-09-29T15:01:54,941][ERROR][o.o.a.u.AlertingException] [opnscluster-n1] Alerting error: MapperParsingException[Invalid [path] value [message_winlogbeat-__1x8H4YoBiU4cj2_sBud9] for field alias [windows.message_winlogbeat-__1x8H4YoBiU4cj2_sBud9]: an alias must refer to an existing field in the mappings.]
[2023-09-29T15:01:54,942][ERROR][o.o.a.t.TransportIndexMonitorAction] [opnscluster-n1] failed to index doc level queries monitor 1x8H4YoBiU4cj2_sBud9. deleting monitor
org.opensearch.alerting.util.AlertingException: Invalid [path] value [message_winlogbeat-__1x8H4YoBiU4cj2_sBud9] for field alias [windows.message_winlogbeat-__1x8H4YoBiU4cj2_sBud9]: an alias must refer to an e
 
 Do we need to do all the mapping ? Is it normal to extend the total field limit to this size ?
 
 
 Thanks for your help.

**Comment by sbcd90** [comment]
hi @mareban , the issue actually is,
```
Invalid [path] value [message_winlogbeat-__1x8H4YoBiU4cj2_sBud9] for field alias [windows.message_winlogbeat-__1x8H4YoBiU4cj2_sBud9]
```
your index do not have a field called `message` but somehow in field mappings the field `windows.message` is mapped to `message`.
it is `completely optional` to specify any mappings.
also, yes, the `total field limit can exceed to this size` but for `winlogbeat` it should not go this much.
i would recommend delete your existing detector, clean up all `.opensearch-sap*` & `.opensearch-alerting*` & `.opendistro-alerting*` & then deploy the detector.

**Comment by mareban** [comment]
Thanks a lot for your help 

So we've tried to delete the detectors and do the cleanup and now, if we try to create a DNS detector we've got an error : detection creation failed, double check the mapping , but the DNS detector is created !

So we've tried to create a windows detector, but it's still not work for US :-( !

We don't know what we can do now, we've upgraded hoping it will fix the problem, no more lot of sap queries indicies Thx, but still cannot create a windows detector on our cluster !

Any other suggestions are welcome ?

Thanks for your help.

[2023-10-01T15:11:34,224][INFO ][o.o.a.u.d.DestinationMigrationCoordinator] [opnscluster-n1] Detected cluster change event for destination migration
[2023-10-01T15:11:34,322][INFO ][o.o.p.PluginsService     ] [opnscluster-n1] PluginService:onIndexModule index:[.opensearch-sap-windows-detectors-queries-000001/zwRkaIhLTwOwGtNBKB7lvA]
[2023-10-01T15:11:34,343][INFO ][o.o.a.u.d.DestinationMigrationCoordinator] [opnscluster-n1] Detected cluster change event for destination migration
[2023-10-01T15:11:34,481][INFO ][o.o.a.u.d.DestinationMigrationCoordinator] [opnscluster-n1] Detected cluster change event for destination migration
[2023-10-01T15:11:45,628][INFO ][o.o.c.s.IndexScopedSettings] [opnscluster-n1] [.opensearch-sap-windows-detectors-queries-000001] updating [index.mapping.total_fields.limit] from [1000] to [5020008]
[2023-10-01T15:11:45,635][INFO ][o.o.a.u.d.DestinationMigrationCoordinator] [opnscluster-n1] Detected cluster change event for destination migration
[2023-10-01T15:12:25,424][INFO ][o.o.a.a.AlertIndices     ] [opnscluster-n1] Index mapping of .opensearch-sap-dns-alerts is updated
[2023-10-01T15:12:25,443][INFO ][o.o.a.a.AlertIndices     ] [opnscluster-n1] Index mapping of .opensearch-sap-dns-alerts-history-2023.10.01-1 is updated
[2023-10-01T15:12:25,454][INFO ][o.o.a.a.AlertIndices     ] [opnscluster-n1] Index mapping of .opensearch-sap-dns-findings-2023.10.01-1 is updated

[2023-10-01T15:34:49,147][INFO ][o.o.c.s.IndexScopedSettings] [opnscluster-n1] [.opensearch-sap-windows-detectors-queries-000001] updating [index.mapping.total_fields.limit] from [1000] to [5020008]
[2023-10-01T15:34:49,172][INFO ][o.o.a.u.d.DestinationMigrationCoordinator] [opnscluster-n1] Detected cluster change event for destination migration
[2023-10-01T15:36:16,167][INFO ][o.o.j.s.JobSweeper       ] [opnscluster-n1] Running full sweep

**Comment by sbcd90** [comment]
hi @mareban , can you please specify the error you get while creating `windows` detector?

**Comment by amsiglan** [comment]
Closing the issue for now as it seems to be fixed. @mareban Feel free to reopen it if you have more concerns.
